# frozen_string_literal: true

communities_list = [
  { name: 'Cape Horn', code: 'CV' },
  { name: 'Lancaster Street', code: 'LS' },
  { name: 'Ran-Dell', code: 'RD' },
  { name: 'Coventry at Waterford', code: 'CW' },
  { name: 'Kings Arms at Waterford', code: 'KA' },
  { name: 'Governours Place at Waterford', code: 'GO' },
  { name: 'Royal Court at Waterford', code: 'RL' },
  { name: 'South Hampton at Waterford', code: 'SO' },
  { name: 'Waterford Professional Center', code: 'OF' },
  { name: 'Beaufort Manor', code: 'BF' },
  { name: 'Crooked Hill Townhomes', code: 'CH' },
  { name: 'Colonial Glen', code: 'CG' },
  { name: 'Paxton Park', code: 'PP' },
  { name: 'Camelot Arms', code: 'CA' },
  { name: 'North Hills', code: 'NH' },
  { name: 'Pleasant Valley Townhomes', code: 'PT' },
  { name: 'Heatherwood', code: 'HW' },
  { name: 'Cool Creek Manor', code: 'CC' },
  { name: 'Cold Springs', code: 'CS' },
  { name: 'Dovertowne', code: 'DT' },
  { name: 'Heritagetowne', code: 'HT' },
  { name: 'Hampton Court', code: 'HC' },
  { name: 'Spring Meadow', code: 'SM' },
  { name: 'Westgate Terrace', code: 'WG' },
  { name: 'Hyde Park', code: 'HP' },
  { name: 'Parkview Place', code: 'PV' },
  { name: 'Brandywine 1', code: 'B1' },
  { name: 'Brandywine 2', code: 'B2' },
  { name: 'Brandywine Townhomes', code: 'BT' },
  { name: 'Woodbridge Apartments', code: 'WA' },
  { name: 'Woodbridge North', code: 'WN' },
  { name: 'Woodbridge Townhomes', code: 'WT' },
  { name: 'Kings Grant Landing', code: 'KG' },
  { name: 'Legends 1', code: 'L1' },
  { name: 'Legends 2', code: 'L2' },
  { name: 'Breezewood', code: 'BW' },
  { name: 'Stony Point', code: 'SP' },
  { name: 'The Meadows', code: 'ME' },
  { name: 'Laketree Manor', code: 'LM' }
]

Community.create(communities_list)
